#!/bin/bash

# Add Env
# Replace the value with your AWS region - eg: us-east-1
export AWS_DEFAULT_REGION=us-east-1
# Replace the value with your AWS account ID
export AWS_ACCOUNT_ID=123456789123
# Replace the value with the container name - eg: webapp
export CONTAINER_NAME=WebApp # 


# Download codedeploy-agent
echo "<<<<< codedeploy-agent start >>>>>"
sudo yum update
sudo yum install ruby -y
sudo yum install wget -y
cd /home/ec2-user
sudo wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
chmod +x ./install

# install & start codedeploy-agent
sudo ./install auto
sudo service codedeploy-agent start
echo "<<<<< codedeploy-agent finish >>>>>"

# install & start docker
echo "<<<<< docker start >>>>>"
sudo yum search docker
sudo yum install docker -y
sudo newgrp docker
sudo usermod -a -G docker ec2-user
sudo systemctl enable docker.service
sudo systemctl start docker.service
echo "<<<<< docker finish >>>>>"


# ECR login
echo "<<<<< ECR login >>>>>"
aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

# pull the new image
echo "<<<<< ECR pull >>>>>"
docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_NAME:latest

# run the container
echo "<<<<< RUN container >>>>>"
docker run -d -p 8501:8501 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_NAME:latest