AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CDN Stack:
  - CloudFront Distribution 
  - Route 53 Hosted Zone Record 

Parameters:
  CertificateArn:
    Type: String
    Description: The ARN of the ACM certificate
  ALBStack:
    Type: String
    Description: ALB stack - imported
  DomainName:
    Type: String
    Description: Your Domain Name
  DomainHostedZoneId:
    Type: String
    Description: Your Domain Name
  HostedZoneRecord:
    Type: String
    Description: The ID of the Route 53 hosted zone
  CustomDomainName:
    Type: String
    Description: The ID of the Route 53 hosted zone
 
Resources:
  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3 
        Aliases: 
          - !Ref CustomDomainName
        Origins:
          - DomainName: 
              Fn::ImportValue: 
                !Sub '${ALBStack}-ALBURL'
            Id: WebAppALBOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPPort: 80
              HTTPSPort: 443
            OriginCustomHeaders:
              - HeaderName: "X-Custom-Header"
                HeaderValue: "cf-alb-webapp"
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: WebAppALBOrigin
          # Cache Policy ID: Managed-Caching Disabled
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          # Origin request policy ID: AllViewerAndCloudFrontHeaders-2022-06
          OriginRequestPolicyId: 33f36d7e-f396-46d9-90e0-52428a34d9dc 
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
  
  # Route 53 A record 
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DomainHostedZoneId
      Name: !Join ['', [!Ref 'HostedZoneRecord',.,!Ref 'DomainName',.]]
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID
        DNSName: !GetAtt CloudFrontDistribution.DomainName

